# Generated by Django 5.2.6 on 2026-05-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApneaSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField()),
                ("baseline_ready", models.BooleanField(default=False)),
                ("baseline_stats", models.JSONField(blank=True, null=True)),
                ("model_config", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ApneaChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("chunk_index", models.IntegerField(default=0)),
                ("ppg_green", models.JSONField(default=list)),
                ("wear_valid", models.BooleanField(null=True)),
                ("wear_label", models.IntegerField(null=True)),
                ("wear_prob", models.FloatField(null=True)),
                ("r_ratio_series", models.JSONField(blank=True, null=True)),
                ("is_baseline", models.BooleanField(default=False)),
                ("beat_results", models.JSONField(blank=True, null=True)),
                ("p_apnea", models.FloatField(null=True)),
                ("p_apnea_smooth", models.FloatField(null=True)),
                ("pred_label", models.IntegerField(null=True)),
                ("pred_status", models.CharField(blank=True, max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="apnea.apneasession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
