# Generated by Django 5.2.6 on 2026-05-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apnea", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apneachunk",
            name="ppg_ir",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="apneachunk",
            name="ppg_red",
            field=models.JSONField(default=list),
        ),
    ]
