# Generated by Django 5.2.6 on 2026-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apnea", "0002_apneachunk_ppg_ir_apneachunk_ppg_red"),
    ]

    operations = [
        migrations.AddField(
            model_name="apneachunk",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
