# Generated by Django 5.2.6 on 2026-04-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "monitoring",
            "0008_protectee_address_protectee_age_protectee_gender_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ImuData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_index", models.IntegerField()),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
                ("sample_rate", models.IntegerField(default=50)),
                ("window_sec", models.IntegerField(default=6)),
                ("samples", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protectee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imu_data",
                        to="monitoring.protectee",
                    ),
                ),
            ],
            options={
                "db_table": "imu_data",
                "ordering": ["start_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["protectee", "start_timestamp"],
                        name="imu_data_protect_4a5c67_idx",
                    ),
                    models.Index(
                        fields=["protectee", "window_index"],
                        name="imu_data_protect_65bd47_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="imu_data_created_aa852f_idx"
                    ),
                ],
            },
        ),
    ]
