# Generated by Django 5.2.6 on 2026-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imudata",
            name="sample_rate",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="imudata",
            name="window_sec",
            field=models.IntegerField(default=12),
        ),
    ]
