# Generated by Django 5.2.6 on 2025-12-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(help_text='워치/앱에서 사용하는 ID (예: watch UUID)', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPGMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('stress', models.FloatField(blank=True, null=True)),
                ('ppg_value', models.FloatField(blank=True, null=True)),
                ('window_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('protectee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.protectee')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['protectee', 'timestamp'], name='monitoring__protect_1011a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('PPG_ALERT', 'PPG 알람'), ('IMU_ALERT', 'IMU 알람'), ('GEO_ALERT', '위치 알람')], max_length=20)),
                ('ppg_threat_detected', models.IntegerField(blank=True, null=True)),
                ('hrv', models.FloatField(blank=True, null=True)),
                ('stress', models.FloatField(blank=True, null=True)),
                ('imu_danger_level', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('zone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('protectee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.protectee')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['protectee', 'timestamp'], name='monitoring__protect_8ef87b_idx'), models.Index(fields=['event_type', 'timestamp'], name='monitoring__event_t_09d03c_idx')],
            },
        ),
    ]
