# Generated by Django 5.2.6 on 2025-12-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hrv',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ppg_threat_detected',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stress',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zone_type',
        ),
        migrations.AlterField(
            model_name='protectee',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='PPGMeasurement',
        ),
    ]
