# Generated by Django 5.2.6 on 2025-12-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_event_hrv_remove_event_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectee',
            name='external_id',
        ),
    ]
