# Generated by Django 5.2.6 on 2025-12-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_remove_protectee_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_usual_route",
            field=models.IntegerField(
                blank=True, help_text="1=평소경로, 0=이탈", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
