# Generated by Django 5.2.6 on 2026-01-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_event_is_usual_route_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectee",
            name="device_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
