# Generated by Django 5.2.6 on 2026-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_protectee_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_usual_route",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meta_json",
        ),
        migrations.AddField(
            model_name="event",
            name="ppg_holding",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectee",
            name="device_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
