# Generated by Django 5.2.6 on 2026-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0006_remove_event_is_usual_route_remove_event_meta_json_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PPG_ALERT", "PPG 알람"),
                    ("IMU_ALERT", "IMU 알람"),
                    ("GEO_ALERT", "GEO 알람"),
                ],
                max_length=20,
            ),
        ),
    ]
