# Generated by Django 5.2.6 on 2026-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectee",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="protectee",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protectee",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="protectee",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
