# Generated by Django 5.2.6 on 2026-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_geoprocesseddata_geotripanomalyresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geoprocesseddata",
            name="accuracy_h",
        ),
    ]
