# Generated by Django 5.2.6 on 2025-12-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("ppg_green", models.JSONField(default=list)),
                ("ppg_ir", models.JSONField(default=list)),
                ("ppg_red", models.JSONField(default=list)),
                ("predictions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
